# Generated by Django 5.1.2 on 2024-10-13 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
