# Generated by Django 5.1.2 on 2024-10-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0005_alter_catimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='catimage',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='catimage',
            name='profession',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
